# Generated by Django 5.1 on 2024-09-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=10)),
                ('expiry', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=1000)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
