# Generated by Django 5.1 on 2024-09-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_makepayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakePayment',
            new_name='Payment',
        ),
    ]
